### ISSUE TITLE
Mettre à jour la preuve formelle

### ISSUE THREAD

**Issue by bzg** [Delegation-numerique-en-sante/covid19-algorithme-orientation#15]
Voir [cette modification](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/pull/9/files) qui modifie la logique de parcours de l'arbre.

cc @denismerigoux

**Comment by denismerigoux** [comment]
Fait dans bba3d6b27c5100099df2da9064e598dd7d9ef417.

**Comment by bzg** [comment]
Merci !
