### ISSUE TITLE
Exécution du pseudo-code

### ISSUE THREAD

**Issue by denismerigoux** [Delegation-numerique-en-sante/covid19-algorithme-orientation#16]
Je commente ici car impossible de commenter les autres issues.

OK je corrige https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/issues/14. Néanmoins dans https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/pull/9 Mauko dit qu'il ne sait pas s'il faut exécuter le pseudo code de haut en bas. C'est l'hypothèse que j'ai prise dans mon modèle, mais du coup ce ne serait pas vrai ? Si le code n'est pas exécuté de haut en bas alors je peux essayer de prouver que toutes les entrées sont accessibles.

**Comment by denismerigoux** [comment]
De la manière dont était présentée le pdf de l'institut Pasteur j'avais l'impression que ça correspondait à une exécution séquentielle, i.e de haut en bas.

**Comment by maukoquiroga** [comment]
J'ai fait pareil pour les `roots` (up-down), mais j'ai inversé les `branches` et les `leaves :

https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-elixir/blob/b6a558df86217c2b671b886c5cbcca774c3b081e/lib/covid19_orientation/test_orientation.ex#L55-L128

**Comment by bzg** [comment]
Oui, je suis aussi parti de l'hypothèse d'une exécution séquentielle.

**Comment by denismerigoux** [comment]
Ok, dans ce cas mon modèle est correct.

**Comment by bzg** [comment]
Merci pour la confirmation.
