### ISSUE TITLE
Proposer une implémentation en Python

### ISSUE THREAD

**Issue by bzg** [Delegation-numerique-en-sante/covid19-algorithme-orientation#18]
L'extraire du code de `covid.py` du répertoire "preuve-formelle"?

cc @denismerigoux

**Comment by maukoquiroga** [comment]
Et la publication de ;'extrait du code maladiecoronavirus.fr ?

**Comment by bzg** [comment]
Je pense que c'est un autre sujet.

**Comment by denismerigoux** [comment]
Vu la très faible taille du code on ne gagne rien à développer un système de compilation pour générer à la fois le Z3 et du Python exécutable à partir de la même source, autant re-développer quelque chose en Python normal. 

D'autant plus que la manière d'encoder les choses en Z3 est très particulière, ça correspond pas du tout au code à exécuter pour traiter les réponses au questionnaire.

**Comment by bzg** [comment]
Pardon, je voulais dire "l'extraire à la main" :)

Si jamais tu penses avoir le temps de re-développer ce code en Python normal, merci !

**Comment by bzg** [comment]
La réimplémentation n'est plus à l'ordre du jour, je ferme cette issue.
