### ISSUE TITLE
Corriger une clause jamais évaluée

### ISSUE THREAD

**Issue by bzg** [Delegation-numerique-en-sante/covid19-algorithme-orientation#19]
On me remonte cette anomalie:
```
25  SI pas de fièvre et (toux OU mal de gorge OU anosmie)
26     SI 0 facteur de gravité mineur => FIN7
27     SI au moins un facteur de gravité mineur OU un facteur pronostique => FIN8
```

Il faudrait inverser les lignes 26 et 27, autrement le clause "OU un facteur pronostique" n'est jamais évaluée.

OK pour vous @maukoquiroga @denismerigoux ?

**Comment by denismerigoux** [comment]
En effet, bien vu ! Ou alors simplement supprimer `au moins un facteur de gravité mineur` à la ligne 27

**Comment by denismerigoux** [comment]
En effet, bien vu ! L'erreur est aussi présente dans le PDF. Inverser les lignes me semble la bonne solution.

**Comment by bzg** [comment]
Merci pour la confirmation, c'est noté.

**Comment by maukoquiroga** [comment]
Je confirme @bzg ! 

Cf. de mon implém :

```elixir
      %Tree{
        operation: &symptomes3/1,
        children: [
          %Tree{key: &fin8/1, operation: &(facteurs_pronostique(&1) >= 1)},
          %Tree{key: &fin8/1, operation: &(facteurs_gravite(&1) >= 1)},
          %Tree{key: &fin7/1, operation: &(facteurs_gravite(&1) == 0)}
        ]
      }
```

**Comment by bzg** [comment]
C'est corrigé définitivement de façon stable depuis [ce commit](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/commit/253989170561537ad227276acf5a1f2b55ddeab2).
