### ISSUE TITLE
Propositions d'amélioration du pseudocode

### ISSUE THREAD

**Issue by judbd** [Delegation-numerique-en-sante/covid19-algorithme-orientation#20]
J'ai implémenté l'algorithme dans une application d'orientation rapide d'usagers hier soir, et le pseudocode m'a bien aidé, cependant, j'ai remarqué quelques améliorations possibles.

Les voici :

```
3  SI (fièvre ET PAS toux) OU (toux ET mal de gorge) OU (toux ET anosmie) OU (fièvre ET diarrhée)
4  SI un facteur de gravité majeur => FIN5
```
1. On peut tester seulement la fièvre + le reste (comme c'était le cas de la 1re version), pourvu de faire passer `16  SI fièvre ET toux` avant cette condition.
2. Le Facteur de gravité majeur est inutile ici puis que le moindre facteur de gravité majeur renvoie vers la `FIN 5` et qu'il est testé un cran plus haut avec `23  SI 1 OU plus facteur de gravité majeur => FIN5`
3. Dans ce contexte, le facteur de diarrhée ne sert à rien car il n'est jamais utilisé, le critère de fièvre suffit pour entrer dans la condition (`fièvre ET PAS toux` et vérifier `fièvre ET diarrhée` étant donné que `diarrhée` utilisé nulle part ailleurs que dans cette condition.

```
25  SI pas de fièvre et (toux OU mal de gorge OU anosmie)
26     SI 0 facteur de gravité mineur => FIN7
27     SI au moins un facteur de gravité mineur OU un facteur pronostique => FIN8
```

On ne rentre jamais dans la condition de la ligne 27 si on a un facteur pronostic défavorable sans facteur de gravité mineur. je propose d'inverser les lignes (cf issue #19 )

Il faudrait également définir une fin par défaut dans le pseudocode.

**Comment by bzg** [comment]
Oui, d'accord avec tous ces points. S'ils sont tous pris en compte, alors on peut aussi supprimer la détection de la diarrhée, contrairement à ce que je dis dans [cette issue](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/issues/21), et _modulo_ la nécessité de collecter l'info pour les statistiques.

> Il faudrait également définir une fin par défaut dans le pseudocode.

Le parcours de l'arbre doit être séquentiel, donc la fin par défaut est la _dernière_ condition. Mais oui, c'est une précision importante à ajouter.

**Comment by bzg** [comment]
Ici aussi, est-ce que tu peux vérifier si ces remarques sont toujours d'actualité par rapport au dernier [arbre de décision](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-arbre-de-decision/blob/master/covid19-orientation-arbre-de-decision.txt)?

**Comment by bzg** [comment]
Ces points ont été tranchés ce matin, le dernier arbre est à jour.
