### ISSUE TITLE
Supprimer des questions et simplifier la saisie de certaines réponses

### ISSUE THREAD

**Issue by judbd** [Delegation-numerique-en-sante/covid19-algorithme-orientation#21]
Dans le contexte d'une orientation rapide des usagers, j'ai remarqué que plusieurs questions du JSON sont facultatives et ne sont jamais utilisées dans l'algorithme :
- Présence ou absence de fièvre (induit par la question de température)
- Température sous les 35,5°C
- Diarrhée

Peut-être qu'elles peuvent être marquées comme facultatives dans la documentation ?

Également, l'IMC semble avoir assez peu d'impact sur le résultat final (= un facteur de pronostic défavorable) et il oblige à l'utilisateur une saisie fastidieuse et au développeur des vérifications liées à une entrée utilisateur (réponses aberrantes, fourchette possible, format de séparateur décimal). Peut-être est-il possible de se passer de ce critère lors d'une qualification rapide ? Ou demander la taille en centimètres plutôt qu'en mètre pour faciliter la saisie ?

**Comment by bzg** [comment]
Merci pour ton retour. Je vois plusieurs sujets distincts:

1. la simplification de la détection de la fièvre
2. la prise en compte de la présence de la diarrhée (impactant _peu_ le parcours de l'arbre)
3. la prise en compte de l'IMC (impactant _peu_ le résultat via les facteurs pronotisque)
4. l'optimisation de l'ergonomie pour la saisie du poids et de la taille

Pour tous ces facteurs, comme tu l'as noté, l'état du questionnaire actuel vient du fait que l'implémentation "mère" de l'algorithme (https://maladiecoronavirus.fr) aide à recueillir des données, en plus du conseil donné à l'utilisateur.

Néanmoins:

1. Pour la fièvre, on pourrait n'avoir qu'une seule question (`>= 39°?`) mais on perd dans ce cas le bénéfice de la détection de ceux qui ne "savent pas"
2. Pour la diarrhée, elle est bien dans l'arbre de décision, à voir si l'institut Pasteur confirme la pertinence
3. Pour l'IMC, il est bien pris en compte comme facteur pronostique, à voir ici aussi si c'est toujours pertinent
4. Pour la simplification de la saisie de l'IMC, on pourrait proposer de saisir un estimation (comme c'est fait dans [le démonstrateur](https://delegation-numerique-en-sante.github.io/covid19-algorithme-orientation/demonstrateur.html)) et/ou de saisir la taille en centimètres

Je remonte tous ces points dans un document que je prépare aujourd'hui pour synthétiser les recommandations que fera la DINUM suite à la formalisation de l'algorithme.

**Comment by judbd** [comment]
1. Pour la fièvre on peut mettre 3 intervalles de température + "je ne sais pas" et se base là dessus plutôt qu'une entrée manuelle (et éliminer la fièvre <35.5 qui ne sert pas).
2. La diarrhée est dans l'arbre de décision mais ne sert jamais car la condition est vérifiée par la simple fièvre #20 . (Mais peut être utile à des fins statistiques)
3. L'IMC est bien pris en compte, je ne le remet pas en cause, mais vu le seuil retenu et la teneur autres critères de pronostic défavorable avec le même poids algorithmique (cancer, maladie rénale, pneumopathie…) ça me parait plus anecdotique en plus d'être fastidieux à rentrer, mais c'est juste un retour orienté "service", je n'ai aucune compétence médicale donc s'il faut absolument le laisser je comprends.
4. Si l'IMC doit être conservée, sa simplification sans saisie utilisateur pourrait être une bonne idée si possible.

**Comment by bzg** [comment]
C'est noté, attends les retours.

**Comment by bzg** [comment]
Peux-tu regarder dans le dernier [l'arbre de décision](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-arbre-de-decision/blob/master/covid19-orientation-arbre-de-decision.txt) si la diarrhée a une influence sur le parcours de l'arbre ?

De mon point de vue oui, mais je peux me tromper.

Si tu penses qu'il faut corriger, tu peux ouvrir une issue sur le dépôt consacré à l'arbre de décision ?

Merci !

**Comment by judbd** [comment]
Dans le dernier arbre on dirait que oui, mais les conditions ont changées ? avant c'était fièvre ET diarrhée qui faisait entre dans le même arbre que fièvre seule (et donc la question sur la diarrhée était inutile)

**Comment by bzg** [comment]
OK, ça me rassure, je commençais à me demander si je n'étais pas fou :)

Oui, l'arbre a changé, ce dépôt permet de suivre l'historique des changements de l'arbre seul.

**Comment by bzg** [comment]
PS: Je me suis permis de reformuler l'issue pour qu'on garde en tête les questions sur l'UX/UI plutôt que celles sur la structure de l'arbre, traitées par ailleurs.

**Comment by bzg** [comment]
Voir aussi https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-arbre-de-decision/issues/1

**Comment by bzg** [comment]
Ce n'est plus à l'ordre du jour pour cette documentation.
