### ISSUE TITLE
Couleurs et compréhension des boutons

### ISSUE THREAD

**Issue by davidbgk** [Delegation-numerique-en-sante/covid19-algorithme-orientation#23]
La couleur actuelle des boutons Non est verte et celle des boutons Oui est orange, ce qui est un code couleur assez inhabituel pour être perturbant pour la personne remplissant ce formulaire (potentiellement exacerbé par la situation de stress) :

<img width="1461" alt="Capture d’écran, le 2020-03-27 à 09 54 51" src="https://user-images.githubusercontent.com/3556/77763257-2d00bf00-7011-11ea-8bf6-81d55f170e7d.png">

Je propose soit des couleurs plus neutres, soit une inversion des couleurs entre le Oui et le Non.

**Comment by maiwann** [comment]
Je plussoie une proposition de couleurs neutres, afin de ne pas inciter l'utilisateur à choisir selon ce qui appelle le plus son oeil mais bien selon le libellé du bouton.

**Comment by davidbgk** [comment]
@bzg un fil sur mastodon à ce sujet https://mastodon.social/@dav/103895271358812547

**Comment by bzg** [comment]
Je suis parti sur une seule couleur (bleu), en ne gardant des couleurs différentes que pour la fin.

Est-ce OK pour vous ?  Merci d'avoir signalé ça.

**Comment by davidbgk** [comment]
Top, merci 👍
