### ISSUE TITLE
Est-ce qu'une fièvre <= 35,4°C doit être considéré comme un facteur de gravité ?

### ISSUE THREAD

**Issue by bzg** [Delegation-numerique-en-sante/covid19-algorithme-orientation#26]
Si oui, facteur de gravité *mineur* ou facteur de gravité *majeur* ?

**Comment by judbd** [comment]
Et est-ce que c'est considéré comme de la fièvre ? Selon les dernières réponses, oui.

**Comment by judbd** [comment]
Il faudrait éditer cette partie du doc :
```
Facteur de gravité mineurs :
    Fièvre >= 39°C
    A indiqué de la fièvre sans renseigner de la température
    Fatigue : alitement > 50% du temps diurne
```
En ajoutant `fièvre <= 35,4`

**Comment by bzg** [comment]
C'est corrigé, merci !
