### ISSUE TITLE
Implémentation à auditer : Formulaire Intelligent Qwesta

### ISSUE THREAD

**Issue by SebastienMUFF** [Delegation-numerique-en-sante/covid19-algorithme-orientation#29]
Nom du porteur de la solution d'orientation : Sébastien MUFF

URL du site principal : www.qwesta-consulting.fr

URL de l'implémentation de l'algorithme d'orientation COVID 19 : https://coronavirus-info-chatbot.qwesta-builder.io/form/4fCIsTFVuFeNmuchQBby/draft

URL du code source publié de son implémentation : https://www.qwesta.fr/public/kdpm59e1kz36/covid-19-isa-vous-informe-6-1-6.json

**Comment by bzg** [comment]
Bonjour, bien reçu, merci.

Collectez-vous des données à partir de ce formulaire ?

**Comment by SebastienMUFF** [comment]
Merci pour votre retour,

Non, ce formulaire est totalement anonymisé : nous ne collectons aucune information personnelle hormis le code postal, nous avons même désactivé l’adressage IP. Les données anonymisées sont chez OVH.

Bonne soirée

 

De : Bastien <notifications@github.com> 
Envoyé : mardi 31 mars 2020 19:49
À : Delegation-numerique-en-sante/covid19-algorithme-orientation <covid19-algorithme-orientation@noreply.github.com>
Cc : SebastienMUFF <sebastien.muff@qwesta.fr>; Author <author@noreply.github.com>
Objet : Re: [Delegation-numerique-en-sante/covid19-algorithme-orientation] Implémentation à auditer : Formulaire Intelligent Qwesta (#29)

 

Bonjour, bien reçu, merci.

Collectez-vous des données à partir de ce formulaire ?

**Comment by bzg** [comment]
J'attire votre attention que ces échanges sont publics et lisibles [ici](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/issues/29), même si vous répondez pas email.

Il y a donc bien des données collectées, celles dont vous dites qu'elles sont "anonymisées" et chez "OVH".

J'ai noté votre demande, j'y répondrai d'ici demain soir. Merci !

**Comment by bzg** [comment]
Une question: est-ce que l'URL `https://coronavirus-info-chatbot.qwesta-builder.io/form/4fCIsTFVuFeNmuchQBby/draft` est l'URL définitive de votre solution?

**Comment by SebastienMUFF** [comment]
Non, nous pouvons la router vers n’importe quelle URL. Nous pouvons aussi très rapidement la mettre à n’importe quelle marque :

Là voici aux couleurs de SIKIM réalisé à l’instant : https://sikim.qwesta-builder.io/form/eOJWFnNd6j9VQxEwrGHy/draft

 

De : Bastien <notifications@github.com> 
Envoyé : mardi 31 mars 2020 20:02
À : Delegation-numerique-en-sante/covid19-algorithme-orientation <covid19-algorithme-orientation@noreply.github.com>
Cc : SebastienMUFF <sebastien.muff@qwesta.fr>; Author <author@noreply.github.com>
Objet : Re: [Delegation-numerique-en-sante/covid19-algorithme-orientation] Implémentation à auditer : Formulaire Intelligent Qwesta (#29)

 

Une question: est-ce que l'URL https://coronavirus-info-chatbot.qwesta-builder.io/form/4fCIsTFVuFeNmuchQBby/draft est l'URL définitive de votre solution?

**Comment by bzg** [comment]
Je propose de fermer cette issue : s'il n'y a pas d'objection d'ici la fin du mois, je la fermerai.

**Comment by bzg** [comment]
Pas d'objection, je ferme.
