### ISSUE TITLE
Validité de la contrainte fièvre => (facteurs_gravite_mineur > 0) ?

### ISSUE THREAD

**Issue by datajms** [Delegation-numerique-en-sante/covid19-algorithme-orientation#31]
Bonjour Bastien,
Super code de preuve formelle !

C'est un détail, mais j'ai l'impression qu'il y a un problème avec la contrainte L29
s.add(Implies(fievre, facteurs_gravite_mineur > 0))

En effet, considérons une personne qui a remplit le questionnaire en déclarant Fièvre:=OUI et une Température de 38.0°C.
1. la L29 de ce code de preuve formelle implique que dans ce cas, on a nécessairement facteurs_gravite_mineur > 0
2. la rubrique "Facteurs de gravité mineurs et majeurs" du [pseudo-code](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/blob/master/pseudo-code.org#arbre-de-d%C3%A9cision) ne comptabilise pas une fièvre à 38.0°C comme un facteur de gravité mineur, donc on peut avoir facteurs_gravite_mineur == 0

Sauf mauvaise compréhension de ma part, il y a une incohérence. Si on veut suivre le pseudo-code, on peut a priori supprimer la contrainte en L29. Non ?

**Comment by bzg** [comment]
Bonjour Jean-Matthieu,

désolé du temps de réponse et merci **beaucoup** pour ton retour.

Ton retour m'a permis d'apporter une précision dans les recommandations d'implémentation: voir la fin de [cette section](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/blob/master/implementation.org#variables-%C3%A0-obligatoirement-sauvegarder-pour-partage) sur les variables.

En réalité, il faut distinguer le paramètre `fièvre` tel qu'il est perçu depuis le questionnaire (qui est une fonction de la réponse "Avez-vous la fièvre" ET de la question sur la température) et le facteur `fièvre` tel qu'il est pris en compte dans l'arbre de décision et dans cette preuve formelle (ainsi que dans [ce fichier de test](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/blob/master/test/choices/algo.clj)).

Dans les deux derniers cas, on n'a besoin que d'un booléen pour la fièvre, et fièvre=1 implique bien un facteur de gravité mineur, donc L29 est pour moi correct.

En revanche, je ne suis pas sûr de comprendre la ligne d'après:

> s.add(Implies(facteurs_gravite_mineur == 2, fievre))

La preuve formelle a été écrite par @denismerigoux qui pourra peut-être répondre - ou me corriger si mon analyse pour la L29 n'est pas correcte.

**Comment by bzg** [comment]
Je reviens sur ce que je viens de dire:

> En revanche, je ne suis pas sûr de comprendre la ligne d'après:

La ligne L30 est correcte: s'il y a deux facteurs de gravité mineurs, au moins l'un des deux est la fièvre.

On peut dire que dans L29 le "implies" est une implication _directe_, dans L30 le "implies" est une implication _indirecte_, les deux étant équivalentes du point de vue logique.

Me reste une question pour Denis: quand je commente L30, j'ai la même sortie pour l'arbre. Est-ce que je me trompe en pensant que cette ligne n'est pas nécessaire à la preuve formelle ?

**Comment by datajms** [comment]
Merci pour tes réponse,
Avec tes précisions sur la différence entre fever et fever_algo, l'incohérence n'existe plus.
De mon côté, ok pour fermer l'issue !

**Comment by bzg** [comment]
OK, merci! Je ferme. @denismerigoux si tu penses qu'il faut rouvrir n'hésite pas.

**Comment by denismerigoux** [comment]
La situation est la suivante : il y a deux facteurs de gravité mineurs possible, l'un des deux étant la présence de fièvre (booléenne). La ligne 30 fait donc sens puisque ce sont les deux _uniques_ facteurs de gravité possibles : si `facteurs_gravite_mineurs == 2`, alors `fievre == True` puisque (par l'absurde) si `fievre == False` on aurait `facteurs_gravite_mineurs < 2`.

@bzg si tu commentes la ligne 30, les théorèmes tiennent toujours en effet. Cela veut dire que la preuve n'utilise pas cette hypothèse. Elle n'est donc pas stricto sensu nécessaire à la preuve formelle mais elle fait partie de la modélisation de la situation, vu que `facteurs_gravite_mineurs` et `fievre` ne prennent pas leurs valeurs indépendamment.

**Comment by bzg** [comment]
Merci pour les précisions, bien compris !
