### ISSUE TITLE
Implémentation à auditer : myCovitest de BOTdesign

### ISSUE THREAD

**Issue by g-bouvet** [Delegation-numerique-en-sante/covid19-algorithme-orientation#36]
Consultez https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/blob/master/referencement.org

- [x] Nom du porteur de la solution d'orientation : BOTdesign
- [x] URL de son site principal : https://botdesign.net/
- [x] URL vers son implémentation de l'algorithme : https://mycovitest.com/
- [x] URL vers le code source de son implémentation : https://github.com/g-bouvet/mycovitest
- [x] L'application est en ligne depuis le : 9/03/2020

Merci de remplir les champs ci-dessus.

**Comment by NicoMaillet** [comment]
Voici les corrections de l'audit de **diag_20200330.csml**

À plusieurs endroits, corriger "s'il vous plait" en "s'il vous pla**î**t"

_l.239_
say "En l'absence de recommandations connues pour les affections pédiatriques (de moins de 15 ans), il faut rechercher un avis médical pour tout symptôme sur les enfants. Si l'état de santé du patient semble inquiétant, appelez le 15."
Il faudrait mieux utiliser la sortie de l'algo **FIN1** (responses_20200330.FIN1)

_l.241_
} else if (parsedAge >= 100 && parsedAge <= 110) {
Est-ce vraiment nécessaire ?

_l.242_
recommendations -> recomm**a**ndations

_l.250_
centimetres -> centim**è**tres

**Comment by NicoMaillet** [comment]
Voici les corrections de l'audit de **diag_20200330_algo.csml**

_l.23-24-25_
```
else if (age >= 15 && age <= 49) remember age_range = "from_15_to_49"
else if (age >= 50 && age <= 69) remember age_range = "from_50_to_69"
else if (age >= 70) remember age_range = "sup_70"
```

Les catégories d'âge sont maintenant >=15 && <=49 mais >=50 && <=**64**
Aussi, la catégorie >=70 ne semble plus utile.

_l.63_
`do hasNoPronosticFactors = (imc <= 30 &&`
doit être 
`do hasNoPronosticFactors = (imc < 30 &&`
**Attention**, dans les facteur prognostiques, il y a `âge >=65`, donc il manque `âge <65` dans cette partie.


_l.103-104-105_
Il faut rajouter le cas douleur et anosmie
`(sore_throat_aches == true && agueusia_anosmia == true) ||`


_l.232-234_
Il faut utiliser **FIN6** et non FIN2

**Comment by bzg** [comment]
Je propose de fermer cette issue : s'il n'y a pas d'objection d'ici la fin du mois, je la fermerai.

**Comment by bzg** [comment]
Pas d'objection, je ferme.
