### ISSUE TITLE
problème avec l'arbre de décision

### ISSUE THREAD

**Issue by vsct-jburet** [Delegation-numerique-en-sante/covid19-algorithme-orientation#4]
Bonjour,

Sur cette partie de l'arbre de décision

```
 3  SI fièvre OU (toux ET mal de gorge) OU (toux ET anosmie) OU (fièvre ET diarrhée)
 4     SI 0 facteur pronostique
 5        SI 0 facteur de gravité mineur
 6           SI moins de 50 ans => FIN2
 7           SINON => FIN3
 8        SINON => FIN3
 9
10     SI 1 OU plus facteurs pronostique
11        SI 0 OU 1 facteur de gravité mineur => FIN3
12        SI au moins 2 facteurs de gravité mineurs => FIN4
13
14     SI un facteur de gravité majeur => FIN5
```

J'ai du mal à comprendre comment on peut arriver à FIN5 (L 14) puisque on rentre forcément dans 0 ou 1+ facteur pronostique

Merci

**Comment by bzg** [comment]
Effectivement. J'ai corrigé le pseudo-code ainsi que le code du démonstrateur et j'ai signalé [cette amélioration](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/issues/5) à apporter au PDF.

Merci beaucoup !
