### ISSUE TITLE
Implémentation à évaluer: Kwalys

### ISSUE THREAD

**Issue by HelaG** [Delegation-numerique-en-sante/covid19-algorithme-orientation#41]
- [ ] Nom du porteur de la solution d'orientation: Kwalys
- [ ] URL de son site principal: https://www.kwalys.com/coronavirus
- [ ] URL vers son implémentation de l'algorithme:
- [ ] URL vers le code source de son implémentation:
- [ ] Date de mise en ligne de l'application:

Veuillez remplir les champs ci-dessus.  Merci !

**Comment by bzg** [comment]
Je propose de fermer cette issue : s'il n'y a pas d'objection d'ici la fin du mois, je la fermerai.

**Comment by bzg** [comment]
Pas d'objection, je ferme.
