### ISSUE TITLE
Implémentation à évaluer: Studia

### ISSUE THREAD

**Issue by HelaG** [Delegation-numerique-en-sante/covid19-algorithme-orientation#43]
- [x] Nom du porteur de la solution d'orientation: Studia Digitale
- [ ] URL de son site principal: 
- [x] URL vers son implémentation de l'algorithme: https://imnetfr.custhelp.com/app/digitalcx-covid-19
- [ ] URL vers le code source de son implémentation: Documentation envoyée par mail
- [ ] Date de mise en ligne de l'application:

Veuillez remplir les champs ci-dessus.  Merci !

**Comment by bzg** [comment]
Je propose de fermer cette issue : s'il n'y a pas d'objection d'ici la fin du mois, je la fermerai.

**Comment by bzg** [comment]
Pas d'objection, je ferme.
