### ISSUE TITLE
Ajouter un identifiant au schéma de données

### ISSUE THREAD

**Issue by bzg** [Delegation-numerique-en-sante/covid19-algorithme-orientation#44]
Pour les besoins de traitement des données, il est utile d'avoir un identifiant unique de type `uuid` pour chaque réponse au questionnaire d'orientation.

C'est une contrainte quasi-indispensable notamment pour ceux qui veulent partager des données anonymisées.

La proposition est d'ajouter cet identifiant à `implementation.org` et au [schéma de données](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-check) qui en résulte.

**Comment by flegoff** [comment]
Note : sur MaladieCoronavirus.fr nous avons une clé session_signature qui est un sha384 d'une valeur générée aléatoirement à chaque début de questionnaire.

Par exemple : `session_signature => '94cf61987922c3a269928e4ba8f82f0a81dc4c5abedbdf8155a78669b428868254ec05eee948633297bf6a6cce1d1630'`

**Comment by bzg** [comment]
OK. J'affine la proposition : ajouter une variable _optionnelle_ `id` au [schéma de données](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-check/blob/master/schema.json) dont le contenu serait un `uuid`.

Ca n'empêcherait pas les producteurs de données d'implémenter d'autres identifiants.
