### ISSUE TITLE
Aligner les valeurs acceptables d'orientation avec celles du doc de Pasteur

### ISSUE THREAD

**Issue by bzg** [Delegation-numerique-en-sante/covid19-algorithme-orientation#45]
Dans la dernière version du document partagé par l'Institut Pasteur, les valeurs acceptables pour la variable `orientation` diffèrent des valeurs de cette documentation.

La proposition est d'aligner les deux documents sur ces valeurs:

```
 - FIN1: less_15
 - FIN2: home_surveillance
 - FIN3: consultation_surveillance_1
 - FIN4: consultation_surveillance_2
 - FIN5: SAMU
 - FIN6: consultation_surveillance_3
 - FIN7: consultation_surveillance_4
 - FIN8: surveillance
```

**Comment by flegoff** [comment]
Note : en pratique la valeur FIN1 ne devrait jamais être transférée dans la mesure où c'est une condition de sortie qui devrait à mon sens interrompre immédiatement la saisie du questionnaire.

**Comment by bzg** [comment]
Oui - au début le schéma ne contenait pas la FIN1 dans la liste des valeurs valables pour `orientation` mais je l'ai [ajoutée](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-check/commit/8df58b2a492d2d795fdf29faf3ea6be47c9ab06e) en me disant qu'un producteur de données pourrait vouloir garder en base de données le nombre de réponses reçues de personnes de moins de quinze ans et communiquer ce chiffre.

Dans l'implémentation du [questionnaire du SIG](https://www.gouvernement.fr/info-coronavirus/orientation-medicale) nous n'envoyons pas les données si le répondant a moins de 15 ans.

**Comment by bzg** [comment]
Fait.
