### ISSUE TITLE
Nouvelle version de l'arbe de décision : l'augmentation des faux négatifs est-elle volontaires ?

### ISSUE THREAD

**Issue by lgrauser** [Delegation-numerique-en-sante/covid19-algorithme-orientation#46]
Bonjour,

En  regardant la nouvelle version de l'arbre décision et notamment l'introduction du XOR en ligne 11, je me rends compte qu'un patient déclarant de la fièvre et de la diarhée ne rentre donc plus dans le cas de la ligne 11 et fini par rentrer dans le test de la ligne 25.
Cela veut donc dire qu'un patient avec de la fièvre et de la diarrhée arrive à la fin FIN8 : probablement un covid.
Ne va-t-on pas augmenter le nombre de faux négatifs ? 
De plus il me semble que ces symptomes peuvent relever d'un Covid.

Cordialement,

Ludovic Grauser

**Comment by bzg** [comment]
Bonjour et merci beaucoup d'avoir remonté cette incohérence - ce "XOR" était resté à la suite de tests exploratoires que j'avais faits (mais auxquels j'avais renoncé, comme [cette implémentation](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/blob/master/src/cljs/choices/custom.cljs#L74) le monde.)

**Comment by lgrauser** [comment]
Du coup aucun des XOR n'est à garder ?
Il y en plusieurs dans le nouvel arbre de décision.

**Comment by bzg** [comment]
Seul le XOR signalé à la ligne 11 est incorrect, il faut garder les autres.
