### ISSUE TITLE
Export des données vers Santé Publique France

### ISSUE THREAD

**Issue by lgrauser** [Delegation-numerique-en-sante/covid19-algorithme-orientation#47]
Bonjour,

Notre implémentation de l'algorithme est finalisée et lancée.
Nous sommes en train de déposer notre code sur github accessible pour pouvoir lancer la review auprès de vous de son implémentation.
Comment doit on faire pour exporter les données vers Santé Publique France ? J'ai vu dans le githb un format JSON, doit on bien partir sur ce format ou est on libre ?
Comment doit se passer le transfert ? 
Est-il possible de traiter cela en https avec BascAuth et restriction d'IP ?
Sinon quelle méthode de transfert préconisez vous ?

Merci pour vos réponses.

Cordialement,

Ludovic Grauser

**Comment by HelaG** [comment]
Bonjour @lgrauser !

Les données sont remontées à l'Institut Pasteur. L'Institut Pasteur définit le format des données et les modalités de transfert (SFPT à priori).

Les ré-utilisateurs de l'algo qui veulent contribuer à la remontée de données signent un contrat avec l'IP. Quel est le nom de votre service / entreprise ? (pour savoir si le contrat votre réutilisation est dans le radar)

**Comment by bzg** [comment]
Bonsoir @lgrauser - une précision, pour le schéma de données à partager, il est défini [ici](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-check/blob/master/schema.json).

**Comment by lgrauser** [comment]
Merci pour le schéma, nous l'avions vu.
Notre solution s'appelle AlloCovid elle est née d'une collaboration entre l'INSERM, e.voyageurs SNCF et Allo-Media. Il s'agît d'un bot téléphonique accessible sur un numéro de téléphone 0806800540.
Comment peut on faire pour obtenir les accès SFTP ?
Doit on d'abord être référencé ?

Merci pour vos réponses.

Ludovic Grauser

**Comment by bzg** [comment]
Je me demandais justement si AlloCovid était déjà en lien avec Pasteur : le plus simple est de continuer cet échange par mail (`bastien.guerry@data.gouv.fr`), nous pourrons vous faire suivre les bons contacts. Merci !

**Comment by bzg** [comment]
Le contact a été pris il y a quelque temps déjà, je ferme cette issue.
