### ISSUE TITLE
Typo dans la documentation sur le nom du virus

### ISSUE THREAD

**Issue by bryan-brancotte** [Delegation-numerique-en-sante/covid19-algorithme-orientation#48]
Bonjour

Dans https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/blob/master/website/algorithme-orientation-covid19.org le nom du virus apparait sous deux forme : ``COVID 19`` (3 fois) vs ``Covid-19`` (11 fois).. Cela a un impact lorsque l'on recherche en texte simple des morceaux de texte de fin dans les implémentations pour s'assurer qu'ils sont corrects (FIN6 à actuellement au moins deux formes).

Je peux faire une PR s'il faut uniquement modifier ``COVID 19`` -> ``Covid-19`` et que la CI/CD fait le reste.

Cordialement

**Comment by bzg** [comment]
Bonjour, merci d'avoir signalé cette incohérence. C'est corrigé (pour `Covid-19`) dans la version actuelle du dépôt, qui sera publiée comme version `2020-06-09` plus tard dans la journée.
